# Generated by Django 5.2.8 on 2025-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
