# Generated by Django 5.2.8 on 2025-11-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
