# Generated by Django 5.2.8 on 2025-11-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
