# Generated by Django 5.2.8 on 2025-11-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
